# 블루-그린 배포용 Values 파일 예시
# 사용법: helm upgrade --install app-name . -f values_bluegreen.yaml

# 기본 설정 상속
global:
  image:
    tag: "v1.2.3"  # 배포할 이미지 태그

# Rollout 활성화
rollout:
  enabled: true
  
  strategy:
    blueGreen:
      # 자동 프로모션 (프로덕션에서는 false 권장)
      autoPromotionEnabled: false
      
      # 30초 후 이전 버전 제거
      scaleDownDelaySeconds: 30
      
      # 프리뷰 환경은 1개 파드만
      previewReplicaCount: 1
      
      # 프로모션 전 분석 활성화
      prePromotionAnalysis:
        enabled: true

  # 프리뷰 서비스 설정
  previewService:
    type: ClusterIP

  # 분석 템플릿 활성화
  analysisTemplate:
    enabled: true
    
    metrics:
      successRate:
        threshold: 0.90  # 개발환경은 90% 성공률
        count: 2
        failureLimit: 1
      
      responseTime:
        threshold: 1.0   # 1초 이하
        count: 2
        failureLimit: 1

# 레플리카 수
replicaCount: 2

# 리소스 설정
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
