# 간단한 블루-그린 배포용 Values 파일 (분석 없이)
# 사용법: helm upgrade --install app-name . -f values_simple_bluegreen.yaml

# 기본 설정
global:
  image:
    tag: "latest"  # 배포할 이미지 태그

# Rollout 활성화 (분석 없이)
rollout:
  enabled: true
  
  strategy:
    blueGreen:
      # 수동 프로모션 (안전하게)
      autoPromotionEnabled: false
      
      # 30초 후 이전 버전 제거
      scaleDownDelaySeconds: 30
      
      # 프리뷰 환경은 1개 파드만
      previewReplicaCount: 1
      
      # 분석 비활성화 (일단 기본 동작만 테스트)
      prePromotionAnalysis:
        enabled: false
      
      postPromotionAnalysis:
        enabled: false

  # 프리뷰 서비스 설정
  previewService:
    type: ClusterIP

  # 분석 템플릿 비활성화
  analysisTemplate:
    enabled: false

# 레플리카 수
replicaCount: 2

# 리소스 설정
resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
