{{- if and .Values.rollout.enabled .Values.rollout.analysisTemplate.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ include "ezl-app-server.fullname" . }}-success-rate
  labels:
    {{- include "ezl-app-server.labels" . | nindent 4 }}
spec:
  metrics:
  # 간단한 웹훅 테스트 (실제 서비스 확인)
  - name: webservice-test
    interval: {{ .Values.rollout.analysisTemplate.metrics.successRate.interval | default "10s" }}
    count: {{ .Values.rollout.analysisTemplate.metrics.successRate.count | default 3 }}
    successCondition: result == "success"
    failureLimit: {{ .Values.rollout.analysisTemplate.metrics.successRate.failureLimit | default 2 }}
    provider:
      web:
        url: "http://{{ include "ezl-app-server.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.port }}/healthz"
        timeoutSeconds: 5
        headers:
          - key: "Content-Type"
            value: "application/json"
        jsonPath: "{$.status}"

  # 간단한 HTTP 상태 코드 체크
  - name: http-status-check
    interval: {{ .Values.rollout.analysisTemplate.metrics.successRate.interval | default "10s" }}
    count: {{ .Values.rollout.analysisTemplate.metrics.successRate.count | default 2 }}
    successCondition: result[0] == 200
    failureLimit: {{ .Values.rollout.analysisTemplate.metrics.successRate.failureLimit | default 1 }}
    provider:
      web:
        url: "http://{{ include "ezl-app-server.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.service.port }}/"
        timeoutSeconds: 10
{{- end }}
