{{- if .Values.rollout.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ezl-app-server.fullname" . }}-preview
  labels:
    {{- include "ezl-app-server.labels" . | nindent 4 }}
    service-type: "preview"
spec:
  type: {{ .Values.rollout.previewService.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (eq (.Values.rollout.previewService.type | default "ClusterIP") "NodePort") .Values.rollout.previewService.nodePort }}
      nodePort: {{ .Values.rollout.previewService.nodePort }}
      {{- end }}
  selector:
    {{- include "ezl-app-server.selectorLabels" . | nindent 4 }}
{{- end }}
